# Generated by Django 4.2.16 on 2024-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=212)),
                ('title_en', models.CharField(max_length=212, null=True)),
                ('title_ru', models.CharField(max_length=212, null=True)),
                ('title_uz', models.CharField(max_length=212, null=True)),
                ('content', models.TextField(max_length=500)),
                ('content_en', models.TextField(max_length=500, null=True)),
                ('content_ru', models.TextField(max_length=500, null=True)),
                ('content_uz', models.TextField(max_length=500, null=True)),
                ('author', models.CharField(max_length=212)),
                ('author_en', models.CharField(max_length=212, null=True)),
                ('author_ru', models.CharField(max_length=212, null=True)),
                ('author_uz', models.CharField(max_length=212, null=True)),
            ],
        ),
    ]
